name: "Exercicio 1"

on:
  push:
  
jobs:
  print_date_ubuntu:
    name: Imprimir datas ubunto
    runs-on: ubuntu-latest
    
    steps:
      - name: Imprimir data 1 ubunto
        run: date

  print_date_windows:
    name: Imprimir datas windows
    runs-on: windows-latest
    
    steps:
      - name: Imprimir data 2 windows
        run: date
  
  print_date_macos:
    name: Imprimir datas macos
    runs-on: macos-latest
    
    steps:
      - name: Imprimir data 3 macos
        run: date

  print_date_ubunto_final:
    name: Imprimir data final ubunto
    runs-on: ubunto-latest
    needs:
      - print_date_ubuntu
      - print_date_windows
      - print_date_macos
        
    steps:
    - name: Imprimir data 4 ubunto
      run: date
