name: "Exercicio 1"

on:
  push:
  
jobs:
  print_date1_ubuntu:
    name: Imprimir data 1 ubunto
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir data 1 ubunto
        run: date

  print_date2_windows:
    name: Imprimir data 2 windows
    runs-on: windows-latest
    steps:
      - name: Imprimir data 2 windows
        run: date
        
  print_date3_macos:
    name: Imprimir data 3 macos
    runs-on: macos-latest
    steps:
      - name: Imprimir data 3 macos
        run: date
  
  print_date4_ubunto:
    name: Imprimir data 4 ubunto
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir data 4 ubunto
        run: date
        needs:
          - print_date1_ubuntu
          - print_date2_windows
          - print_date3_macos
  
